server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: new-entity
          uri: https://github.com/rovala/Microservicio
          search-paths: config-data
  application:
    name: config-service